fix: Fix linting and msw import errors

diff --git a/scripts/build-api b/scripts/build-api
--- a/scripts/build-api
+++ b/scripts/build-api
@@ -23,3 +23,14 @@ then
 fi
 
 orval --config ./orval.config.ts
+
+if [ -f src/api/api.schemas.ts ]
+then
+  echo "Orval has successfully generated the required files in src/api. Initiating linting..."
+  yarn eslint ./src/api --ext ts,tsx --report-unused-disable-directives --fix
+  echo "Linting process completed!"
+else
+  echo "Error: Missing files and/or incorrect file names in src/api after running Orval!"
+  echo "Please check that orval.config.ts is set up correctly."
+  exit 1
+fi
