refactor: simplify code; fix: prioritize access token passed as argument

diff --git a/scripts/fetch-api-spec b/scripts/fetch-api-spec
--- a/scripts/fetch-api-spec
+++ b/scripts/fetch-api-spec
@@ -4,68 +4,48 @@
 # personal access token, that has read access to
 # https://github.com/canonical/openfga-admin-openapi-spec repository,
 # is required to be passed, either via GITHUB_ACCESS_TOKEN in .env.local or
-#  as the sole argument to this bash script.
-
-USE_ENV_LOCAL_ACCESS_TOKEN=false
-
-if [ -f .env.local ]
-then
-  ENV_LOCAL_ACCESS_TOKEN=$(grep -o "^[^#]*GITHUB_ACCESS_TOKEN=.*" .env.local | cut -d'=' -f2)
-  if [ -n "$ENV_LOCAL_ACCESS_TOKEN" ]
-  then
-    ACCESS_TOKEN="$ENV_LOCAL_ACCESS_TOKEN"
-    USE_ENV_LOCAL_ACCESS_TOKEN=true
-  fi
-fi
-
-if [ $USE_ENV_LOCAL_ACCESS_TOKEN = false ]
-then
-  if [ -n "$1" ]
-  then
-    ACCESS_TOKEN="$1"
-  else
-    echo "Please provide a valid github personal access token!"
-    echo "Pass it via GITHUB_ACCESS_TOKEN in .env.local or as the sole argument of this script!"
-    exit 1
-  fi
-fi
+# as the sole argument to this bash script.
 
 API_SPEC_VERSION="main"
-USE_ENV_LOCAL_API_SPEC_VERSION=false
+source .env
+source .env.local
+
+if [ -z "$API_SPEC_VERSION" ]
+then
+  echo "Error: API spec version got overridden with an empty string from .env or .env.local!"
+  exit 1
+fi
+
+if [ -n "$1" ]
+then
+  GITHUB_ACCESS_TOKEN="$1"
+fi
+
+if [ -z "$GITHUB_ACCESS_TOKEN" ]
+then
+  echo "Error: A valid github personal access token was not found!"
+  echo "Pass it via GITHUB_ACCESS_TOKEN in .env.local or as the sole argument of this script."
+  exit 1
+fi
+
 OUTPUT_FILE="openapi.yaml"
-
-if [ -f .env.local ]
-then
-  ENV_LOCAL_API_SPEC_VERSION=$(grep -o "^[^#]*API_SPEC_VERSION=.*" .env.local | cut -d'=' -f2)
-  if [ -n "$ENV_LOCAL_API_SPEC_VERSION" ]
-  then
-    API_SPEC_VERSION="$ENV_LOCAL_API_SPEC_VERSION"
-    USE_ENV_LOCAL_API_SPEC_VERSION=true
-  fi
-fi
-
-if [ $USE_ENV_LOCAL_API_SPEC_VERSION = false ] && [ -f .env ]
-then
-  ENV_API_SPEC_VERSION=$(grep -o "^[^#]*API_SPEC_VERSION=.*" .env | cut -d'=' -f2)
-  if [ -n "$ENV_API_SPEC_VERSION" ]
-  then
-    API_SPEC_VERSION="$ENV_API_SPEC_VERSION"
-  else
-    echo "WARNING: No API spec version is specified! API spec will be downloaded from main branch."
-  fi
-fi
-
 API_SPEC_URL="https://raw.githubusercontent.com/canonical/openfga-admin-openapi-spec/$API_SPEC_VERSION/openapi.yaml"
 
-OPENAPI_YAML_CONTENT=$(curl -H "Authorization: token $ACCESS_TOKEN" \
+OPENAPI_YAML_CONTENT=$(curl -H "Authorization: token $GITHUB_ACCESS_TOKEN" \
   -H "Accept: application/vnd.github.v3.raw" \
   -L $API_SPEC_URL)
 
-if [[ "$OPENAPI_YAML_CONTENT" == "404: Not Found"* ]] || [[ "$OPENAPI_YAML_CONTENT" == "400: Invalid request"* ]]
+if [[ "$OPENAPI_YAML_CONTENT" =~ ^(404: Not Found|400: Invalid request) ]]
 then
-  echo "Error while trying to download openapi.yaml file!"
+  echo "Error: Can't download openapi.yaml file!"
   echo "Please check that both the access token and the API spec version are valid."
   exit 1
 fi
 
-echo "$OPENAPI_YAML_CONTENT" > $OUTPUT_FILE
+if echo "$OPENAPI_YAML_CONTENT" > $OUTPUT_FILE
+then
+    echo "The content has been successfully written to $OUTPUT_FILE!"
+else
+    echo "Error: Couldn't write the content to $OUTPUT_FILE!"
+    exit 1
+fi
